version: 2

project_name: shed-sidecar

before:
  hooks:
    - go mod tidy

builds:
  - id: sidecard
    main: ./cmd/sidecard
    binary: sidecard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: sidecarctl
    main: ./cmd/sidecarctl
    binary: sidecarctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: binaries
    ids:
      - sidecard
      - sidecarctl
    files:
      - install.sh
      - sidecar.service
      - README.md
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"
